merge_protections:
  - name: VM1 deployment aggregate pass
    if: true
    success_conditions:
      - label = bug
  - name: VM1 deployment aggregate fail
    if: true
    success_conditions:
      - label = enhancement
merge_protections_settings:
  reporting_method: deployments
  post_comment: false
